### ISSUE TITLE
running  BlurryModalSegue wihtout cocoa-pods

### ISSUE THREAD

**Issue by onderozcan** [Citrrus/BlurryModalSegue#24]
is there any way to run BlurryModalSegue without using cocoa-pods ?

**Comment by jasontrask** [comment]
You just need to manually add the BlurryModalSegue's dependencies into your project as well:

https://github.com/Adrian2112/UIImage-BlurredFrame
https://github.com/m1entus/MZAppearance
QuartzCore iOS framework
